/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during development and is committed here
// so TypeScript can resolve Next types before the first local run.
