import { Badge } from "@/components/ui/badge";

const toneByStatus: Record<string, "green" | "yellow" | "red" | "blue" | "purple" | "coral" | "muted"> = {
  pagado: "green",
  activo: "green",
  entregado: "green",
  admin: "green",
  finanzas: "green",
  project_manager: "purple",
  desarrollador: "blue",
  marketing: "blue",
  solo_lectura: "muted",
  cliente: "yellow",
  pendiente: "yellow",
  media: "yellow",
  alta: "coral",
  urgente: "red",
  baja: "blue",
  interesado: "yellow",
  por_vencer: "yellow",
  vencido: "red",
  cancelado: "red",
  pausado: "red",
  lead: "purple",
  en_desarrollo: "purple",
  en_progreso: "purple",
  mantenimiento: "blue",
  revision: "coral",
  contacto: "blue",
  reunion_agendada: "purple",
  negociacion: "coral",
  ganado: "green",
  perdido: "red",
  confirmado: "blue",
  completado: "green",
  brief: "blue",
  contrato: "purple",
  factura: "green",
  propuesta: "coral",
  recurso: "yellow",
  otro: "muted",
  normal: "green",
  sin_fecha: "muted",
  visible: "green",
  oculto: "muted",
  archivado: "yellow",
  finalizado: "muted",
  activa: "green"
};

export function StatusBadge({ status }: { status: string }) {
  return <Badge tone={toneByStatus[status] ?? "muted"}>{status.replaceAll("_", " ")}</Badge>;
}
